package:
  name: envbin
  epoch: 0
  version: v0.0.8-9-g6eee80f-dirty
  description: Exposes its environment over an API
  url: https://github.com/mt-inside/envbin
  copyright:
    - paths:
        - "*"
      license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - build-base
      - go
      - just
      - git
      - libusb-dev
      - pkgconf
pipeline:
  - name: Build
    runs: |
      # build, rather than install, to be able to control output dir
      just build-daemon-ci -o "${{targets.destdir}}/usr/bin/envbin"
