name: test

on: push

jobs:
  test:
    name: Lint and test
    runs-on: 'ubuntu-latest'
    steps:
      - name: Libusb
        run: apt install libusb-1.0-0-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install tools
        run: just tools-install

      - name: Find tools
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Lint & Test
        run: just test
